name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3 # Latest version use karna better hai
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Directory check aur Permissions
          if [ ! -d "devops-portfolio" ]; then
            git clone https://github.com/${{ github.repository }}.git devops-portfolio
          fi
          
          cd devops-portfolio
          
          # Git pull se pehle local changes discard karna (Conflict se bachne ke liye)
          git fetch --all
          git reset --hard origin/main
          
          # Docker Commands
          sudo docker stop portfolio || true
          sudo docker rm portfolio || true
          
          # Build with cache cleaning (taaki storage full na ho)
          sudo docker build -t portfolio .
          
          # Container Run
          sudo docker run -d -p 80:80 --name portfolio portfolio
          
          # Unused images clean karna taaki EC2 ki disc space na bhare
          sudo docker image prune -f