name: Deploy Portfolio Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-portfolio
            # Naya code pull karein
            git pull origin main
            
            # Nayi image build karein
            sudo docker build -t portfolio .
            
            # Purana container stop aur remove karein (agar chal raha ho)
            sudo docker stop portfolio-container || true
            sudo docker rm portfolio-container || true
            
            # Naya container start karein
            sudo docker run -d -p 80:80 --name portfolio-container portfolio